#PBS -l select=1:ncpus=1:mem=12gb
#PBS -l walltime=06:00:00

start_time=$SECONDS
cd /rds/general/project/bacterial_evo_genomics/live/gps_annotations_4_2_2020/gps_gubbins_runs/gps_tn916_run_free

module load anaconda3/personal

source activate

conda activate insertion_site_analysis

bash ../ISA/bash/flank_search_only.sh ../gps_tn916_run_free/gps_tn916 ../tmp_dna_dir/ ../act_compos/referoo.fasta. \
 ../gps_tn916_run_free gps_tn916 ../flank_lengths.txt ../ ../../strep_reference_fasta/strep_ref_database \
../contig_bounds/  


end_time=$(( SECONDS - start_time ))
echo "${end_time} seconds" > gps_tn916_flanks_extraction_time.txt


