#PBS -l select=1:ncpus=1:mem=2gb
#PBS -l walltime=6:00:00

start=$SECONDS

module load anaconda3/personal

source activate

conda activate insertion_site_analysis

cd /rds/general/project/bacterial_evo_genomics/live/gps_annotations_4_2_2020/gps_gubbins_runs

bash ./ISA/bash/isa_pipeline.sh ./gps_run_data/gps ./gps_run_data/tn916.fasta \
7000 gps_tn916_run gps_916 no

duration=$(( SECONDS - start ))

echo $duration > mega_run_time.txt
