#PBS -l select=1:ncpus=1:mem=12gb
#PBS -l walltime=16:00:00

start=$SECONDS

module load anaconda3/personal 

source activate 

conda activate insertion_site_analysis 

cd /rds/general/project/bacterial_evo_genomics/live/gps_annotations_4_2_2020/gps_gubbins_runs

bash ./ISA/bash/isa_pipeline.sh ./gps_run_data/gps ./gps_run_data/tn1207.fasta \
2000 gps_mega_run4 gps_mega ./ 500 ./act_compos_mega/ no /rds/general/project/bacterial_evo_genomics/live/gps_annotations_4_2_2020/strep_reference_fasta/strep_ref_database

cd ./gps_mega_run4

bash ../ISA/bash/flank_search_only.sh ../gps_mega_run4/gps_mega ../tmp_dna_dir/ ../act_compos_mega/referoo.fasta. \
../gps_mega_run4 gps_mega ../flank_lengths.txt ../ ../../strep_reference_fasta/strep_ref_database

duration=$(( SECONDS - start ))

echo $duration > mega_run_time.txt
